name: Deploy-Netlify

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: github environment to deploy to
        required: true
      artifact-name:
        description: "The name of the artifact to download"
        required: true
        type: string

jobs:
  deploy_app:
    name: Deploy app to Netlify
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download web-app artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-cli@v2
        id: netlify
        with:
          # note that the --json flag has been passed so we can parse outputs
          args: deploy --json --prod --dir "./dist" --message "Deploy from GitHub Actions [${{ github.sha }}]"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_PROJECTID }}
      - name: Parse NETLIFY_OUTPUT JSON
        run: |
          echo "The URL where the logs from the deploy can be found"
          echo "${{ fromJson(steps.netlify.outputs.NETLIFY_OUTPUT).logs }}"
          echo ""
          echo "the URL of the draft site that Netlify provides"
          echo "${{ fromJson(steps.netlify.outputs.NETLIFY_OUTPUT).deploy_url }}"
          echo ""
          echo "the URL of the "real" site, set only if `--prod` was passed"
          echo "${{ fromJson(steps.netlify.outputs.NETLIFY_OUTPUT).url }}"
