name: Deploy-Vercel

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: github environment to deploy to
        required: true
      artifact-name:
        description: "The name of the artifact, which contains the static files to deploy"
        required: true
        type: string
      app-folder:
        description: "The path of the app to deploy"
        required: true
        type: string

jobs:
  deploy_app:
    name: Deploy app to Netlify
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Download web-app artifact
        uses: actions/download-artifact@v4
        with:
          name: "feed-it-later-artifact"
          path: ${{ format('{0}/dist', inputs.app-folder) }}

      - name: Deploy to Vercel
        working-directory: ${{ inputs.app-folder }}
        run: npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORGID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECTID}}
