name: Deploy-Netlify -- Secrets

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: github environment to deploy to
        required: true
      env-file-content:
        type: string
        description: "The content of the .env file to use for the deployment"
        required: true
jobs:
  deploy_app:
    name: Deploy app to Netlify
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Save .env file
        run: |
          echo "${{ inputs.env-file-content }}" > .env
      - name: Install Netlify CLI
        run: npm install --global netlify-cli@latest
      - name: Link Netlify site
        run: netlify link --id ${{ vars.NETLIFY_PROJECTID }}
      - name: Upload secrets to Netlify
        run: netlify env:import .env --auth "${{ secrets.NETLIFY_PAT }}" --replace-existing
