name: Deploy-Netlify -- Secrets

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: github environment to deploy to
        required: true
jobs:
  deploy_app:
    name: Deploy app to Netlify
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Save .env file
        run: |
          echo "${{ secrets.RUNTIME_ENV }}" > .env
      - name: Install Netlify CLI
        run: npm install --global netlify-cli@latest
      # - name: Link Netlify site
      #   run: netlify link --id ${{ vars.NETLIFY_PROJECTID }} --auth "${{ secrets.NETLIFY_PAT }}"
      - name: Link project (do not use netlify-cli, because it requires user interaction )
        run: |
          mkdir -p .netlify
          echo "{\"siteId\": \" ${{ vars.NETLIFY_PROJECTID }}\"}" > ".netlify/state.json"
      - name: Upload secrets to Netlify
        run: netlify env:import .env --auth "${{ secrets.NETLIFY_PAT }}" --replace-existing
